### PR TITLE
Feature / App Store Rating Pop Up

### PR DESCRIPTION
**Pull request by eshwartm**

### CODE REVIEW

**Comment by eshwartm** [comment]
Please let me know about improvements required to the code. Thank you.

**Comment by eshwartm** [comment]
Issue #181

**Comment by eshwartm** [comment]
Hi @jorgeblacio, there is an issue. 

I am trying to run the app on my iPhone. I don't have a paid Apple Developer Account. 
So when I run the app using the `Personal Team` credentials, there is an error saying `Your Development Team <team name> doesn't have iCloud and Push Notification capabilities.` It 
seems these capabilities need a paid account.

For this particular issue of `Feature / App Rating Pop Up`, I can run the app on the simulator which is fine. But is there some other way I could run the app on my phone so that I can test any feature or fix I am making on this app? My email is `eshwar.ramesh@gmail.com`

**Comment by eshwartm** [comment]
@jorgeblacio Regarding changing the StoreKit pop up text color -- unfortunately, this is what is stopping me - https://stackoverflow.com/questions/57763132/skstorekitreviewcontroller-and-darkmode

**Comment by jorgeblacio** [comment]
You are right, that is automatically done. Thanks this is a great collaboration. I'll merge it.

**Pull request merged**
